### ISSUE TITLE
Search Scraper empty responses

### ISSUE THREAD

**Issue by jmaloy46** [epctex-support/tiktok-search-scraper#1]
Hello, it seems the TikTok Search Scraper stoped working as expected. Now the majority of searches preformed by the scrapper are responding with log lines like 

```
2024-05-28T19:57:32.577Z WARN  BasicCrawler: Reclaiming failed request back to the list or queue. We got blocked (empty response)
2024-05-28T19:57:32.579Z     at BasicCrawler.requestHandler (file:///usr/src/app/src/main.js:59:19) {"id":"5ECO5z7BQuxIQHU","url" ...
```

Ending of logs shows the following metrics 

```
2024-05-28T19:59:35.083Z ERROR BasicCrawler: Request failed and reached maximum retries. Error: We got blocked (empty response)
2024-05-28T19:59:35.085Z     at BasicCrawler.requestHandler (file:///usr/src/app/src/main.js:59:19)
2024-05-28T19:59:35.087Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-28T19:59:35.089Z     at async BasicCrawler._runRequestHandler (/usr/src/app/node_modules/@crawlee/basic/internals/basic-crawler.js:645:9)
2024-05-28T19:59:35.090Z     at async wrap (/usr/src/app/node_modules/@apify/timeout/index.js:52:21) {"id":"gaCeTLsMyEsCo4n","url":"https://www.tiktok.com/api/search/general/full/?keyword=Booze%2Bcruise%2Binfluencers%2Bin%2BJersey%2BCity&offset=0","method":"GET","uniqueKey":"https://www.tiktok.com/api/search/general/full?keyword=Booze%2Bcruise%2Binfluencers%2Bin%2BJersey%2BCity&offset=0"}
2024-05-28T19:59:35.117Z INFO  BasicCrawler: All requests from the queue have been processed, the crawler will shut down.
2024-05-28T19:59:35.429Z INFO  BasicCrawler: Final request statistics: {"requestsFinished":1,"requestsFailed":20,"retryHistogram":[1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,20],"requestAvgFailedDurationMillis":491,"requestAvgFinishedDurationMillis":1922,"requestsFinishedPerMinute":0,"requestsFailedPerMinute":9,"requestTotalDurationMillis":11743,"requestsTotal":21,"crawlerRuntimeMillis":125535}
2024-05-28T19:59:35.431Z INFO  BasicCrawler: Error analysis: {"totalErrors":20,"uniqueErrors":1,"mostCommonErrors":["20x: We got blocked (empty response) (file:///usr/src/app/src/main.js:59:19)"]}
2024-05-28T19:59:35.432Z INFO  BasicCrawler: Finished! Total 21 requests: 1 succeeded, 20 failed. {"terminal":true}
```

This isn't the case for all requests, just the vast majority of them. Wondering what could be the issue here as it was working a few weeks ago. Any insight would be extremely helpful.

**Comment by tugkan** [comment]
Hey @jmaloy46 ! 

Thanks for reaching out. Can you please a Run ID so that we can check what might be going wrong there?

Best

**Comment by jmaloy46** [comment]
Thanks for the quick response. Here is the run id for the associated logs

`g2igNJdcMn9ryC08r`

**Comment by tugkan** [comment]
@jmaloy46 Thank you! We just tried out the actor, and it worked okay. This problem usually occurs when the actor cannot get the TikTok Cookie properly. Unfortunately, TikTok has increased its protection bar quite high in the last couple of weeks. Can you please try the actor with Residential Proxy and let us know how it goes?

**Comment by jmaloy46** [comment]
Hey! I tried locally with residential proxies and it seemed to work well. 

Id: dbBpqYzMpBnBUUATF

When updating my calling code and running via AWS Lambda invocation, I still ran into these issues, even with residential proxies enabled.

Id: kXfa541bdvGfMamlp

But after trying again (via Lambda) it worked. 

Id: or8knJgTPBA84Mafb

The test input vs actual execution input is identical aside from the startUrls. Wondering if there is anymore insight into how I can ensure consistency (or at least increase % of successful reqs)? All help is greatly appreciated! Thanks

**Comment by tugkan** [comment]
Hey @jmaloy46 !

Thank you for your patience, and sorry to have you wait. We are still investigating and fixing the issue. This issue is not stalled but we are actively working on it. 

I will keep you posted.

**Comment by tugkan** [comment]
Hey @jmaloy46 !

Thank you again for the wait. Since the first day, the Engineering Team has been working on the actor and trying to identify the issue.

The actor is working properly, but TikTok increased its IP-filtering capability dramatically. It is blocking the IPs a lot even if they are coming from Residential Networks. Of course, Residential proxies tend to block less than the data center ones. However, still problematic I can tell.

There are a couple of options here:

1) Having better-qualified proxies rather than Apify, maybe even getting Unblocker proxies such as this [one](https://oxylabs.io/products/web-unblocker) or [this](https://brightdata.com/solutions/rotating-proxies).

2) Keep all the proxy-related maintenance to the publisher by using PPR actors such as this [one](https://apify.com/apidojo/tiktok-scraper). In these PPR actors, the publisher is responsible for providing the data on your side, you only pay for what you get and don't need to tackle this kind of thing.

I hope this makes sense for you.
Best
